import type { Metadata } from "next";
import "./globals.css";
import LenisScroller from "./LenisScroller";

export const metadata: Metadata = {
  title: "Ghina's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Use link tag to import fonts */}
        <link
          href="https://fonts.googleapis.com/css2?family=Alfa+Slab+One&family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="font-inter bg-black">
      <LenisScroller />
        {children}
      </body>
    </html>
  );
}
