import type { Metadata } from "next";
import "./globals.css";
import LenisScroller from "./LenisScroller";
import { Inter } from "next/font/google";
import { Alfa_Slab_One } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter", // opsional kalau mau pakai CSS variable
});

const alfaSlabOne = Alfa_Slab_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-alfa", // opsional
});

export const metadata: Metadata = {
  title: "Ghina's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${alfaSlabOne.variable}`}>
      <body className="font-inter bg-black">
        <LenisScroller />
        {children}
      </body>
    </html>
  );
}
